/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.github.jeddict.ai.components;

import dev.langchain4j.agent.tool.ToolExecutionRequest;
import io.github.jeddict.ai.util.UIUtil;
import static io.github.jeddict.ai.util.UIUtil.FONT_MONOSPACED;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import org.json.JSONObject;
import static ste.lloop.Loop.on;

/**
 *
 * @author ste
 */
public class ToolExecutionPane extends javax.swing.JPanel {
    /**
     * Creates new form ToolExecutionPane
     */
    public ToolExecutionPane(final ToolExecutionRequest execution, final String result) {
        initComponents();

        nameLabel.setText(execution.name());
        final JSONObject arguments = new JSONObject(execution.arguments());
        on(arguments.keySet()).loop((key) -> {
            argumentsPanel.add(createParamChip(key, arguments.getString(key)));
        });
        resultTextArea.setText(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        argumentsPanel = new javax.swing.JPanel();
        resultPanel = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(UIUtil.COLOR_JEDDICT_MAIN, 3)));
        setName("root"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        headerPanel.setName("headerPane"); // NOI18N
        headerPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setFont(UIUtil.FONT_HEADER);
        nameLabel.setForeground(UIUtil.COLOR_JEDDICT_MAIN);
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(ToolExecutionPane.class, "ToolExecutionPane.name.text")); // NOI18N
        nameLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        nameLabel.setName("name"); // NOI18N
        headerPanel.add(nameLabel, java.awt.BorderLayout.NORTH);

        argumentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        argumentsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        argumentsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        headerPanel.add(argumentsPanel, java.awt.BorderLayout.CENTER);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        resultPanel.setBackground(new java.awt.Color(250, 251, 255));
        resultPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20), javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(224, 224, 224))));
        resultPanel.setName("resultPane"); // NOI18N
        resultPanel.setLayout(new java.awt.BorderLayout());

        resultLabel.setFont(UIUtil.FONT_HEADER);
        resultLabel.setForeground(new java.awt.Color(150, 150, 150));
        org.openide.awt.Mnemonics.setLocalizedText(resultLabel, org.openide.util.NbBundle.getMessage(ToolExecutionPane.class, "ToolExecutionPane.resultLabel.text")); // NOI18N
        resultPanel.add(resultLabel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        resultTextArea.setEditable(false);
        resultTextArea.setBackground(new java.awt.Color(250, 251, 255));
        resultTextArea.setColumns(20);
        resultTextArea.setFont(UIUtil.FONT_NORMAL_TEXT);
        resultTextArea.setLineWrap(true);
        resultTextArea.setRows(5);
        resultTextArea.setWrapStyleWord(true);
        resultTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        resultTextArea.setName("result"); // NOI18N
        jScrollPane1.setViewportView(resultTextArea);

        resultPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(resultPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private JPanel createParamChip(String name, String value) {
        JPanel chip = new JPanel();
        chip.setName("chip");
        chip.setBackground(new Color(241, 243, 245));
        chip.setBorder(new CompoundBorder(
            new LineBorder(new Color(222, 226, 230), 1),
            new EmptyBorder(4, 10, 4, 8)
        ));

        JLabel label = new JLabel("<html><font color='#d63384'><b>" + name + ":</b></font> " + value + "</html>");
        label.setName("argument");
        label.setFont(FONT_MONOSPACED);
        chip.add(label);
        return chip;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel argumentsPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables
}
