/**
 * Copyright 2025-2026 the original author or authors from the Jeddict project
 * (https://jeddict.github.io/).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.jeddict.ai.components;

import dev.langchain4j.agent.tool.ToolExecutionRequest;
import io.github.jeddict.ai.util.UIUtil;
import java.awt.Component;
import javax.swing.JPanel;
import org.json.JSONObject;
import static ste.lloop.Loop.on;

/**
 * A component for displaying tool execution details.
 */
public class ToolExecutionPane extends javax.swing.JPanel {

    public ToolExecutionPane(final ToolExecutionRequest execution, final String result) {
        initComponents();

        nameLabel.setText(execution.name());
        final JSONObject arguments = new JSONObject(execution.arguments());
        on(arguments.keySet()).loop((key) -> {
            argumentsPanel.add(createArgumentChip(key, arguments.getString(key)));
        });
        resultTextArea.setText(result);
        resultTextArea.setRows(Math.min(5, resultTextArea.getLineCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        argumentsPanel = new javax.swing.JPanel();
        resultPanel = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        resultScrollPane = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(UIUtil.COLOR_JEDDICT_MAIN, 3)));
        setMaximumSize(new java.awt.Dimension(2147483647, 350));
        setName("root"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        headerPanel.setName("headerPane"); // NOI18N
        headerPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setFont(UIUtil.FONT_HEADER);
        nameLabel.setForeground(UIUtil.COLOR_JEDDICT_MAIN);
        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(ToolExecutionPane.class, "ToolExecutionPane.name.text")); // NOI18N
        nameLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        nameLabel.setName("name"); // NOI18N
        headerPanel.add(nameLabel, java.awt.BorderLayout.NORTH);

        argumentsPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        argumentsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        headerPanel.add(argumentsPanel, java.awt.BorderLayout.CENTER);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        resultPanel.setBackground(new java.awt.Color(250, 251, 255));
        resultPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(224, 224, 224))));
        resultPanel.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        resultPanel.setName("resultPane"); // NOI18N
        resultPanel.setLayout(new java.awt.BorderLayout());

        resultLabel.setFont(UIUtil.FONT_HEADER);
        resultLabel.setForeground(new java.awt.Color(150, 150, 150));
        org.openide.awt.Mnemonics.setLocalizedText(resultLabel, org.openide.util.NbBundle.getMessage(ToolExecutionPane.class, "ToolExecutionPane.resultLabel.text")); // NOI18N
        resultLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        resultPanel.add(resultLabel, java.awt.BorderLayout.PAGE_START);

        resultScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultScrollPane.setMaximumSize(new java.awt.Dimension(32767, 200));
        resultScrollPane.setMinimumSize(new java.awt.Dimension(16, 25));

        resultTextArea.setEditable(false);
        resultTextArea.setBackground(new java.awt.Color(250, 251, 255));
        resultTextArea.setColumns(20);
        resultTextArea.setFont(UIUtil.FONT_NORMAL_TEXT);
        resultTextArea.setLineWrap(true);
        resultTextArea.setText(org.openide.util.NbBundle.getMessage(ToolExecutionPane.class, "ToolExecutionPane.resultTextArea.text")); // NOI18N
        resultTextArea.setWrapStyleWord(true);
        resultTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultTextArea.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        resultTextArea.setMinimumSize(new java.awt.Dimension(103, 87));
        resultTextArea.setName("result"); // NOI18N
        resultScrollPane.setViewportView(resultTextArea);

        resultPanel.add(resultScrollPane, java.awt.BorderLayout.CENTER);

        add(resultPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private JPanel createArgumentChip(final String name, final String value) {
        return new ArgumentChip(name, value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel argumentsPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables
}
